NAME= BeVexed

TYPE= APP

SRCS= AboutWindow.cpp \
ImageAlert.cpp \
Preferences.cpp \
App.cpp \
Grid.cpp \
MainWindow.cpp \
TileView.cpp \
TimerView.cpp

RDEFS= BeVexed.rdef

LIBS= be translation $(STDCPPLIBS)

APP_VERSION = 1.1

include $(BUILDHOME)/etc/makefile-engine
