NAME= BeVexed

TYPE= APP

SRCS= AboutWindow.cpp \
ImageAlert.cpp \
Preferences.cpp \
App.cpp \
Grid.cpp \
MainWindow.cpp \
TileView.cpp

LIBS= be translation

APP_VERSION = 1.1

include $(BUILDHOME)/etc/makefile-engine
